# Elova - Workflow Observability Platform
# Super Simple Docker Compose Setup
#
# 1. Copy this file: cp docker-compose.simple.yml docker-compose.yml
# 2. (Optional) Change port 3000 below if it's already in use
# 3. Run: docker compose up -d
# 4. Open http://localhost:3000 and complete setup

version: '3.8'

services:
  elova:
    image: ghcr.io/philipphaunstetter/n8n-analytics:latest
    container_name: elova
    restart: always
    ports:
      # Edit this line to change the port: "PORT:3000"
      # Examples: "8080:3000", "3001:3000", "5000:3000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GENERIC_TIMEZONE=UTC
      - TZ=UTC
    volumes:
      - elova_data:/home/node/.elova
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  elova_data: