version: '3.8'

services:
  elova:
    build:
      context: .
      dockerfile: Dockerfile
    image: elova:latest
    container_name: elova
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_TYPE=${DATABASE_TYPE:-postgresql}
      - DATABASE_URL=postgresql://elova:${POSTGRES_PASSWORD:-elova_password}@postgres:5432/elova
      - AUTH_TYPE=${AUTH_TYPE:-simple}
      - AUTH_SECRET=${AUTH_SECRET:-your-super-secure-secret-minimum-32-characters-long}
      - N8N_HOST=${N8N_HOST:-}
      - N8N_API_KEY=${N8N_API_KEY:-}
      - SYNC_FREQUENCY_EXECUTIONS=${SYNC_EXECUTIONS:-15m}
      - SYNC_FREQUENCY_WORKFLOWS=${SYNC_WORKFLOWS:-6h}
      - SYNC_FREQUENCY_BACKUPS=${SYNC_BACKUPS:-24h}
      - NEXT_PUBLIC_ENABLE_DEMO_MODE=${DEMO_MODE:-false}
      - NEXT_PUBLIC_ENABLE_DEV_AUTH=${DEV_AUTH:-false}
    volumes:
      - elova_data:/app/data
      - elova_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elova_network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:15-alpine
    container_name: elova-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=elova
      - POSTGRES_USER=elova
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-elova_password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups/postgres:/backups
    networks:
      - elova_network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elova -d elova"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: elova-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-elova_redis}
    volumes:
      - redis_data:/data
    networks:
      - elova_network
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: elova-proxy
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - elova
    networks:
      - elova_network
    profiles:
      - with-proxy

volumes:
  elova_data:
    driver: local
  elova_logs:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  elova_network:
    driver: bridge