# Elova - Workflow Observability Platform
# SQLite-based Docker Compose Configuration
#
# This is the main docker-compose.yml for the repository
# Uses SQLite database (no separate database service needed)

version: '3.8'

services:
  elova:
    image: ghcr.io/philipphaunstetter/n8n-analytics:latest
    container_name: elova
    restart: unless-stopped
    ports:
      - "${ELOVA_PORT:-3000}:1234"
    environment:
      # Application settings
      - NODE_ENV=production
      - PORT=1234
      
      # Timezone configuration
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
      - TZ=${TZ:-UTC}
      
      # Database configuration (SQLite-based)
      - DATABASE_TYPE=sqlite
      
      # Optional: n8n connection (can be configured via web interface)
      - N8N_HOST=${N8N_HOST:-}
      - N8N_API_KEY=${N8N_API_KEY:-}
      
      # Feature flags
      - ELOVA_DEMO_MODE=${ELOVA_DEMO_MODE:-false}
      # First run detection should be based on volume state, not hardcoded
      # - ELOVA_FIRST_RUN=true  # Removed - let init script detect this
    volumes:
      # SQLite database and application data stored here - fixed path
      - elova_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  elova_data:
    driver: local
